### ISSUE TITLE
account name confusion

### ISSUE THREAD

**Issue by Mihai-Ac** [MicrosoftLearning/mslearn-cognitive-vision#1]
#### Step: 6 to 9

Description of issue:
The instructions for steps 7 through 9 " replace the SUFFIX token in the Storage Account name with your initials or another value to ensure the account name is globally unique" are unclear. Initially sounded like there was the need to create a new suffix every time a new command was ran to be globally unique.

![image](https://user-images.githubusercontent.com/110993710/230927985-10fd8d66-dea9-465c-8ddf-074bcbe27e0a.png)

Suggestion: 

It would be clearer if there was the mention that the account name to be used in steps 7 through 9 is the one created for the first time on step 6.

**Comment by kylebunting** [comment]
I reworked the wording on each step to reference the name of the account created in step 6.
