### ISSUE TITLE
Add Step to add Public Access Level in Storage

### ISSUE THREAD

**Issue by zzulueta** [MicrosoftLearning/mslearn-cognitive-vision#10]
# Module: (https://microsoftlearning.github.io/mslearn-cognitive-vision/instructions/05-exercise-explore-image-analysis.html#provision-azure-resources)
#### Step: 05

Description of issue
Cannot set Public access level: Container (anonymous read access for containers and blobs). We must add step to change Allow Blob anonymous access to Enabled

Repro steps:
Following steps 6-7 requires you to set Container (anonymous read access for containers and blobs). But it will not be possible because we didnt not put the step above.

**Comment by ivorb** [comment]
This repo is no longer used or maintained
