### ISSUE TITLE
Cannot Add Existing Azure ML Workspace from the same subscription

### ISSUE THREAD

**Issue by zzulueta** [MicrosoftLearning/mslearn-cognitive-vision#11]
# Module: [07](https://microsoftlearning.github.io/mslearn-cognitive-vision/instructions/07-exercise-train-custom-object-detection-model.html)
#### Step: 2

Description of issue
If we have an existing data labeling project already from an existing Azure ML Workspace, we cannot select that in the datasets

Repro steps:

1.
1.
1.

**Comment by ivorb** [comment]
This repo is no longer used or maintained
