### ISSUE TITLE
Evaluation Run would fail on evaluation images

### ISSUE THREAD

**Issue by zzulueta** [MicrosoftLearning/mslearn-cognitive-vision#12]
# Module: 07 https://microsoftlearning.github.io/mslearn-cognitive-vision/instructions/07-exercise-train-custom-object-detection-model.html#train-the-custom-object-detection-model
#### Step: 09

Description of issue:
Evaluation would fail with the following error messags:
1. Evaluation failed with internal error: Prediction for https://stmslearnvision.blob.core.windows.net/evaluation-images/image17.jpg failed with code: InputDownloadFailed, message: Could not read from the provided uri.
2. Prediction for https://stmslearnvision.blob.core.windows.net/evaluation-images/image02.jpg failed with code: InputDownloadFailed, message: Could not read from the provided uri.
3. Prediction for https://stmslearnvision.blob.core.windows.net/evaluation-images/image47.jpg failed with code: InputDownloadFailed, message: Could not read from the provided uri.

Repro steps:
1. Followed all the steps but evaluation failed.
2. Evaluation would succeed if labelling was done in AML and a new COCO file was created
3. Evaluation would also succeed if a new dataset was created and the COCO file in #2 was used.
4. It seems the eval-labels.json is improper
[eval-labels.json](https://github.com/MicrosoftLearning/mslearn-cognitive-vision/files/14181827/eval-labels.json)
![Screenshot 2024-02-06 224442](https://github.com/MicrosoftLearning/mslearn-cognitive-vision/assets/41460714/e2ff2e22-6601-4397-b45c-224debd6b822)

**Comment by ivorb** [comment]
This repo is no longer used or maintained
