### ISSUE TITLE
Vision Studio sign-in

### ISSUE THREAD

**Issue by Mihai-Ac** [MicrosoftLearning/mslearn-cognitive-vision#2]
#### Step: 1 and 2
![image](https://user-images.githubusercontent.com/110993710/230932173-dd8a58b8-93f8-48b0-be61-ee7ce9b4e130.png)

**Description of issue**
When opening this page for the first time, the student is not signed in, and because of that the **Get started with Vision** screen is not showing up. 
This is what it is shown:
![image](https://user-images.githubusercontent.com/110993710/230933036-db0506b9-d284-4ee3-9e58-cc08aea1eb92.png)

**Suggestion**: 
Ideally, the student would sign in first before getting access to this page. 
Also, it is worth noting that if the student has access to different azure directories, the correct one for this exercise should be chosen/confirmed. This is how the instructions would look : 
1. In a web browser, navigate to [Vision Studio](https://portal.vision.cognitive.azure.com/).
2. Sign in with your account, and make sure you are using the same directory as the one where you have created the cog-ms-learn-vision resource.
3. On the Vision Studio home page, select View all resources under the Getting started with Vision heading.

**Comment by kylebunting** [comment]
The steps have been updated as suggested.
