### ISSUE TITLE
different number of loaded photos

### ISSUE THREAD

**Issue by Mihai-Ac** [MicrosoftLearning/mslearn-cognitive-vision#3]
#### Step: 4

Description of issue

The number of photos loaded in the photo-album differs from the number of photos from the screenshot in the exercise. This led me to re-check the steps to make sure that I did everything right and there was no mistake.,
Exercise image with numbers (90 photos) :
![image](https://user-images.githubusercontent.com/110993710/230935270-7e08167d-f079-40bd-ad37-be68b3edc6fe.png)

Image displayed in the exercise with different number of photos (109 photos)
![image](https://user-images.githubusercontent.com/110993710/230938937-e2ceaaba-44b2-4335-a37e-463b0b524350.png)

**Suggestion** :  inform the student that the number of images might vary

**Comment by kylebunting** [comment]
The screenshot has been updated to reflect the expected number of images, and language was added to the upload process to provide the number of images.
