### ISSUE TITLE
durationInMinutes values are too low 

### ISSUE THREAD

**Issue by Mihai-Ac** [MicrosoftLearning/mslearn-cognitive-vision#4]
## Lab/Demo: 05-exercise-explore-image-analysis.md and 07-exercise-train-custom-object-detection-model.md

Description of issue
durationInMinutes values are too low (for lab 05 it´s 15 and for lab 07 it´s 20).

Repro steps:
After running the lab several times, I was able to average a 40 minutes time for the completion of lab 05.

For lab 07, it was never less than 120 minutes as there were 2 big issues :  

1)When creating a Azure ML Data Labeling project, the newly created workspace takes more than 1 hour to populate (even with trying in different browsers and restarting PC, I couldn´t find something that would reduce this waiting time) (Create an Azure Machine Learning data-labeling project->Step 6
![image](https://user-images.githubusercontent.com/110993710/230941234-4b2576d7-c84c-4ec0-9ee5-a71090088898.png)

2) Training the _**fruitdetector**_ model takes around 1 hour to complete
![image](https://user-images.githubusercontent.com/110993710/230941654-857e25bb-d1f2-4006-8022-f954a6b364f0.png)

I understand that these are related to the tool and not necessarily with the lab, but the correct expectation related to the duration of the lab should be set.

**Comment by kylebunting** [comment]
I've updated the duration for each lab accordingly.
