### ISSUE TITLE
different number of images in the datasets

### ISSUE THREAD

**Issue by Mihai-Ac** [MicrosoftLearning/mslearn-cognitive-vision#5]
#### Step: 9

Description of issue
The number of images in the lab is different from the one loaded during the exercise.
Lab is counting 68 images
![image](https://user-images.githubusercontent.com/110993710/230942804-9b337956-0279-4de6-83c4-adcc8648125c.png)

The images available in the training_images dataset : 53

Suggestion : 
If the number of images vary and change, then this should be mentioned in the instructions, and lead the student to focus on the 12 required images that need to be pre-labeled.
If the number is fixed, then the values in the lab should be updated.

**Comment by kylebunting** [comment]
The screenshot and wording were updated to reflect the correct number of images in the dataset.
