### ISSUE TITLE
Evaluation error

### ISSUE THREAD

**Issue by Mihai-Ac** [MicrosoftLearning/mslearn-cognitive-vision#6]
#### Step: 07.The initial Status of the model training job will be Queued. Within a minute or two, you should see the status change to Training after selecting Refresh.

The fruitdetector custom model training status is highlighted.

It can take about an hour for the training to complete. Image Analysis 4.0 models can be accurate with only a small set of training data, but they take longer to train than previous models. You can periodically select Refresh to look for an updated status. When model training has been completed, the status will change to Succeeded*.
Description of issue

Issue : The **_fruitdetector_** model completes training successfully , but the evaluation fails. It fails both if the evaluation is done with the training run, or if the evaluation is done after the training scenario has been completed.
![image](https://user-images.githubusercontent.com/110993710/231145585-27d3edec-1f57-4ad8-8c4b-fecf52d94dd6.png)

I ran the model training and the evaluation together and separately several times, the error is the same

Regards,
Mihai

**Comment by kylebunting** [comment]
@Mihai-Ac, I have run through this two more times and cannot reproduce the error with the evaluation dataset. I get a successful evaluation result each time.
