### ISSUE TITLE
Terminology issues in explore-cognitive-services-vision

### ISSUE THREAD

**Issue by PatrickFarley** [MicrosoftLearning/mslearn-cognitive-vision#7]
# Module: explore-cognitive-services-vision
#### Step: all?

Description of issue

We don't use "Cognitive Services for Vision" or "Vision Services" in our docs or marketing material, so this could be confusing. The product group is "Cognitive Services" or "Azure Cognitive Services". The SKU (the product within cog svcs) is "Computer Vision" or "Azure Computer Vision". The service (a particular set of operations that the SKU does) being used here is "Image Analysis". So we would say "Explore Azure Computer Vision" or "Explore Image Analysis," for example.

**Comment by kylebunting** [comment]
Exercises updated to change project name references to either "Image Analysis" or "Azure Computer Vision."

**Comment by kylebunting** [comment]
Updated units to change project name references to either "Image Analysis" or "Azure Computer Vision." Units are in the Azure DevOps repo: https://microsoftdigitallearning.visualstudio.com/Courseware/_git/LP_for_standalone_modules?version=GBmaster&path=/Modules/M07-explore-cognitive-services-vision/includes
