### ISSUE TITLE
Exercise 1 feedback

### ISSUE THREAD

**Issue by ivorb** [MicrosoftLearning/mslearn-cognitive-vision#8]
In order of appearance in lab:

- when creating my container, hit this error: 

    "The request may be blocked by network rules of storage account. Please check network rule set using 'az storage account show -n accountname --query networkRuleSet'.
    If you want to change the default action to apply when no rule matches, please use 'az storage account update'.

    Removing the `--auth-mode login` allowed for creation, and the rest of the lab worked fine.

- nit: Step 2 under CORS setting needs formatting of “Settings” fixed
- Images zip also has a `_MACOSX` folder in it containing folders with hidden DS_Store files. Normal images folder also has the normal DS_Store files, which just looks unpolished and are unnecessary for the lab. Remove mac files from the downloadable zip.
- Nit: code in OCR needs additional indentation for style attributes

**Comment by kylebunting** [comment]
@ivorb, I can remove `--auth-mode login` from the creation of the storage account containers, but in my account, that presents a warning. Not an issue, but something to be aware of, and I can still create the container, so that is better than an error in some environments.

```
There are no credentials provided in your command and environment, we will query for account key for your storage account.
It is recommended to provide --connection-string, --account-key or --sas-token in your command as credentials.

You also can add `--auth-mode login` in your command to use Azure Active Directory (Azure AD) for authorization if your login account is assigned required RBAC roles.
For more information about RBAC roles in storage, visit https://docs.microsoft.com/azure/storage/common/storage-auth-aad-rbac-cli.

In addition, setting the corresponding environment variables can avoid inputting credentials in your command. Please use --help to get more information about environment variable usage.
```

**Comment by kylebunting** [comment]
Feedback addressed:

- I removed `--auth-mode login` from the creation of containers
- Fixed formatting of **Settings** in step 2 of the CORS section
- Recreated `images.zip` to remove `_MACOSX` folder and `.DS_Store` files.
- Fixed indentation for JSON code under OCR section
